name: 'H-Extend'

on:
  #push:
  schedule:
    # UTC time (国内 UTC+8)
     - cron: '30 4 */3 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    #runs-on: macos-latest
    runs-on: macos-10.15

    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
#         - name: 'Set up Python'
#           uses: actions/setup-python@v2
#           with:
#             python-version: '3.9.10'

        - name: 'Install requirements'
          run: |
            pip3 install -r ./requirements.txt
            pip3 install undetected-chromedriver
            
        - name: 'Working'
          env:
            USER_ID: ${{ secrets.USER_ID }}
            PASS_WD: ${{ secrets.PASS_WD }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}

          run: |
            python3 ./main-h.py
